@extends('layouts.app')
@section('title', 'Staff | Studio 3 Dance Plano TX')
@section('content')

    <x-banner banner="banner-staff.jpg" alt="staff member leading young dancers" position="top" heading="staff"/>

    <div class="container mont my-5">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 row-cols-lg-4 mt-5">
           <x-teacher image="staff-brenda.jpg" tag="brenda" name="Brenda Wilder, Director" bio="Brenda began dancing at a young age in her hometown of McComb, Mississippi. She graduated from Southern Methodist University with a BFA in Dance, a minor in Physical Education and Secondary teaching certification. Upon graduation, Brenda developed a dance program at Sunset High School, choreographed musicals and coached the Drill Team and Cheerleading Squad. <br><br> Brenda began teaching dance in the Dallas/Plano/Carrollton area in college and opened Studio 3 Dance in the fall of 1998. She is passionate about dance and her love for children. Her focus is on creating a positive and welcoming environment for young dancers and their families." />
            <x-teacher image="staff-allison.jpg" tag="allison" name="Allison Clark" bio="Allison trained in ballet, tap, jazz, lyrical and pointe at Studio 3 Dance. She was a member of the Shepton Stallionettes and Plano West Royales Drill Teams where she was also a Senior Lieutenant. After graduating from Plano West, Allison choreographed routines and taught drill team officer camps for Starmakers Dance and Performance Camps. She assisted and taught at Studio 3 Dance during the summer before joining the staff in 2011.
<br><br>
Allison has taken master classes from various professional instructors/choreographers in Texas, South Carolina, Las Vegas, Chicago and New York. Allison is a Baylor University graduate with a degree in Elementary Education and is a teacher for Plano ISD. Allison is blessed to have grown up in a dancing family and is thrilled to be part of the staff at Studio 3 Dance." />
            <x-teacher image="staff-becky.png" tag="becky" name="Becky Beck" bio="Becky Beck has been teaching dance in the DFW area for over 30 years. She has become known as a “technique specialists” to dancers of all levels and ages. Former students have gone on to receive college dance scholarships, national and local dance competition titles, year-long scholarships at Broadway Dance Center in New York and the Edge Performing Arts Center in L.A., and have been accepted to summer dance programs nationwide. One former dance student received the prestigious Presidential Scholarship. Four former students have been in the top 30 on SYTYCD and two were featured on the show. Other students have gone on to become dance studio owners, dance instructors, and professional dancers. Beck has taught master classes locally and nationally to private studios, high schools, colleges, and on convention circuits. She was an adjunct faculty dance instructor at Richland, Eastfield, and Navarro Colleges.
<br><br>
Beck’s choreography has won national awards at dance competitions. In addition, she has won numerous “Best Choreography” awards at the local, state, and national level. Beck was a guest choreographer for the Dallas Mavericks’ Dancers for over 7 years. She has also choreographed for aspiring pop singers, classical artists, commercials, college dance programs, high schools, musicals, and individual soloists.
<br><br>
As a professional dancer, Becky danced for J. David Kirby’s Dance Energy and Max Stone’s Citijazz. She performed in numerous industrials including Mary Kay, Target, Coke Light, and Gridiron. Beck appeared on national and international television. She was a feature dancer for an infomercial for “Curves.” She served as dance captain in the musical “Pippin” and on tour in Europe in 1993-94. She performed at numerous award shows, beauty pageants, and dance festivals. She has appeared in ancespirit Magazine and NCA Danz numerous times. Beck was a featured dancer in the pilot “Hip Hop Jamz” filmed in L.A. In addition, she was a dance model for college catalogs and appeared in instructional dance videos. Becky has a B.A. from U.T.D. and an Associate’s Degree from Richland College." />
            <x-teacher image="staff-sally.jpg" tag="sally" name="Sally Johnson" bio="Sally Johnson is a former professional ballet dancer, having won a scholarship to the upper Royal Ballet School in London where she continued her training and represented the Royal Academy of Dance. She performed with the Royal Opera, London Festival Ballet and the Kirov Ballet. Sally then danced under contract as a soloist with the Festival Ballet De Monte Carlo, Irish Ballet Company, and the Royal Ballet of Flanders for ten years. After touring America twice she settled in Dallas and started work with Richland College where she co-directed the Dance Department for twenty-five years. While there, she won the Humanities Haggard award and was recognized for outstanding service and excellence in teaching. Sally continues to teach and choreograph for Studio 3 Dance." />
            <x-teacher image="staff-katherine.jpg" tag="katherine" name="Katherine Woolston" bio="Katherine began dancing at the age of two and has been teaching since she was 17 years old. She has choreographed for Richardson High School's Eaglette Drill team and Theater Department.
<br><br>
Katherine was on the NCA All Star Performance team and was awarded the Superstar Award for Drill Team in High School. She performed in the Macy's Thanksgiving Parade in New York and in the Aloha Bowl in Hawaii.
<br><br>
Katherine studied at Richland College where she was a student instructor for the Jazz Department. She also attended and studied dance at Stephen F. Austin University and The University Of North Texas. She has taken numerous master classes in NYC, dance conventions and teacher training workshops. Katherine joined the Studio 3 Dance staff in 2001." />
            <x-teacher image="staff-adriana.jpg" tag="adriana" name="Adriana Aguilar Ruland" bio="Adriana Aguilar began dancing at the age of 4 at Vivra Jazz Studio in El Salvador. There she was a part of the studio's company and traveled to cities nearby to perform. She moved to the United States at the age of 12 where she continued her dance training at Studio 3 Dance. Adriana was part of Studio 3's competition teams. She was also a member of the Jasper Jazz Drill Team, where she was a part of its Elite Company and Planoette Drill Team where she was a part of the Hip Hop and Jazz/ Contemporary) Elite Lines. She was also honored by her peers with the title of 'Miss Drill Team'. After high school, Adriana attended Texas State University and was a part of 'Creation In Motion Touring Ensemble for Young Audiences'.
<br><br>
            Adriana is trained in various styles of dance but teaches mostly Hip Hop and Musical Theatre. Adriana is happy to be part of her home studio's staff since 2016. Adriana's time away from the studio is spent with her husband (Matt) and 2 daughters (Emmarose and Violet)." />
            <x-teacher image="staff-ashleigh.jpg" tag="ashleigh" name="Ashleigh Sandler" bio="Born and raised in Upstate New York, Ashleigh started dancing when she was 3 years old and became a competition performer at age 9. During her high school years she started assistant-teaching and transitioned to a primary teacher soon after graduating. She attended two years of Teacher Training School through Dance Masters of America, is a certified acrobatic-dance teacher through Acrobatic Arts, and continues to learn new techniques and teaching methods at the annual Dance Teacher Summits in New York and California and the Texas Association Teachers of Dancing convention. She is also a certified instructor with Rhythm Works Integrative Dance.
<br><br>
Ashleigh moved to Texas in 2015. She lives in Arlington with her husband, Brian, and two daughters, Evaline and Brielle. She is excited to keep growing her dance family here!" />
{{--            <x-teacher image="staff-danyelle.jpg" tag="danyelle" name="Danyelle Kerrigan" bio="Originally from Omaha, Nebraska, Danyelle grew up in the competitive dance circuit where she has received numerous regional and national awards as both a dancer and choreographer. With a degree in PR & Advertising from the University of Nebraska at Omaha, Danyelle spends most of her days providing outsourced marketing and social media management to dance-related organizations. Danyelle also does freelance choreography, which has helped high school and collegiate teams to multiple Top 10 finishes at national competitions and numerous state championships for her alma mater, Skutt Catholic High School, for which Danyelle was also the coach while in college.--}}
{{--<br><br>--}}
{{--Danyelle has taught at Studio 3 since 2018. She is currently certified in Alixa Flexibility Modules 1 & 2. When she’s not living and breathing dance, she spends her time with husband (Jim), son (Timothy), daughter (Stevie) and dog (Nellie)." />--}}
            <x-teacher image="staff-sam.jpg" tag="samantha" name="Samantha Hebert" bio="Samantha was born and raised in Plano, TX where she danced at Studio 3 from 2003 to 2020. During her high school years, Samantha served as Captain of the Shepton Stallionettes, as well as Junior Lieutenant and Captain of the Plano West Royales. After graduating from Plano West, Samantha spent the next two years dancing as a Kilgore College Rangerette. Samantha has continued working on her education at the University of Oklahoma and Texas Women’s University. Samantha is so excited to be back at Studio 3 but now as a staff member!" />
{{--            <x-teacher image="" tag="" name="" bio="" />--}}
        </div>

    </div>

@endsection
